definitions:
  identity.Member:
    description: User account information
    properties:
      address:
        description: 钱包地址
        type: string
      contact:
        description: 社交账号
        items:
          type: string
        type: array
      created_at:
        type: integer
      description:
        description: 描述
        type: string
      discord:
        description: discord 账号
        type: string
      email:
        type: string
      identity:
        description: SeeDao中的身份或角色
        items:
          type: string
        type: array
      metadata:
        description: 其他信息
        items:
          $ref: '#/definitions/identity.MemberMetadata'
        type: array
      nickname:
        description: 昵称
        type: string
      projects:
        description: 参与项目
        items:
          type: string
        type: array
      updated_at:
        type: integer
    type: object
  identity.MemberMetadata:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  mvc.DataResult:
    description: 返回结果
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/blob/{key}:
    get:
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: ""
      summary: Get blob data
      tags:
      - example
  /api/v1/sgn:
    get:
      consumes:
      - application/json
      description: 按照交易时间进行降序排序
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 获取sgn信息列表
      tags:
      - sgn
  /identity/v1:
    get:
      consumes:
      - application/json
      description: Get all members
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: size
        in: query
        name: size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mvc.DataResult'
      summary: Get all members
      tags:
      - Identity
    post:
      consumes:
      - application/json
      description: Insert member
      parameters:
      - description: member
        in: body
        name: member
        required: true
        schema:
          $ref: '#/definitions/identity.Member'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mvc.DataResult'
      summary: Insert member
      tags:
      - Identity
  /identity/v1/{address}:
    delete:
      consumes:
      - application/json
      description: Delete member
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mvc.DataResult'
      summary: Delete member
      tags:
      - Identity
    get:
      consumes:
      - application/json
      description: Get member by address
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mvc.DataResult'
      summary: Get member by address
      tags:
      - Identity
    put:
      consumes:
      - application/json
      description: Update member
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      - description: member
        in: body
        name: member
        required: true
        schema:
          $ref: '#/definitions/identity.Member'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mvc.DataResult'
      summary: Update member
      tags:
      - Identity
  /identity/v1/range/{addresses}:
    get:
      consumes:
      - application/json
      description: Get members by addresses
      parameters:
      - description: addresses
        in: path
        name: addresses
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mvc.DataResult'
      summary: Get members by addresses
      tags:
      - Identity
swagger: "2.0"
