name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: go-swag
      uses: yegorrybchenko/go-swag-action@v0.1
      with:
        command: init -d ./internal/apiserver,./internal/member,./pkg/mvc -o ./internal/apiserver/docs

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
